import { useState } from "react";
import { interviewService } from "../../services/interviewService";

export default function OfferLetterGen({ application }) {
  const [form, setForm] = useState({ start_date: "", salary: "", hiring_manager: "" });
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState(null);

  async function handleSend() {
    if (!form.start_date || !form.salary || !form.hiring_manager) return setError("Fill in all fields.");
    setSending(true);
    setError(null);
    try {
      await interviewService.submitApproval(application.interviewId, true);
      setSent(true);
    } catch (err) {
      setError(err.message);
    } finally {
      setSending(false);
    }
  }

  if (sent) return <div className="card" style={{ background: "var(--accent-light)", color: "#085041", fontSize: 13 }}>✓ Offer letter generated by AI and sent.</div>;

  return (
    <div className="card">
      <p className="card-title">Generate offer letter</p>
      <div className="form-group"><input className="form-input" type="date" value={form.start_date} onChange={(e) => setForm((f) => ({ ...f, start_date: e.target.value }))} /></div>
      <div className="form-group"><input className="form-input" placeholder="Annual salary" value={form.salary} onChange={(e) => setForm((f) => ({ ...f, salary: e.target.value }))} /></div>
      <div className="form-group"><input className="form-input" placeholder="Hiring manager" value={form.hiring_manager} onChange={(e) => setForm((f) => ({ ...f, hiring_manager: e.target.value }))} /></div>
      {error && <p className="form-error">{error}</p>}
      <button className="btn btn-primary btn-block" onClick={handleSend} disabled={sending}>{sending ? "Generating with AI…" : "Generate & send offer"}</button>
    </div>
  );
}